version: "3.7"

services:
   app:
      build: .
      restart: unless-stopped
      container_name: wakeonlan
      environment:
         - APP_KEY=secret
         - APP_PORT=2938
      volumes:
         - data:/app/data
      network_mode: host

volumes:
   data:
